### ISSUE TITLE
Is config via labels on target container supported for job-run?

### ISSUE THREAD

**Issue by chenseanxy** [mcuadros/ofelia#109]
In the "Docker labels configurations" sections of README, it implies other types like `job-run` are not supported. 

> it is possible to configure `job-exec` by setting labels configurations on the target container

However in docs/jobs, configuring `job-run` by target container label is clearly shown as an example:

```bash
docker run -it --rm \
    --label ofelia.enabled=true \
    --label ofelia.job-run.sync-rclone.schedule="@daily" \
    --label ofelia.job-run.sync-rclone.command="sync remote" \
    --label ofelia.job-run.sync-rclone.user="rclone-user" \
        rclone:latest
```

To my understanding, this is not supported at the moment, so docs should probably be updated to avoid confusion.

**Comment by Trane9991** [comment]
Yes, thanks for reporting this. This is the typo. `job-run` supported as labels only on `ofelia` container itself.

**Comment by mumrau** [comment]
Might I ask @Trane9991 , why is that?

**Comment by Trane9991** [comment]
Hey, @mumrau could you please clarify your question a bit?

**Comment by mumrau** [comment]
Why cannot we specify `job-run` or `job-local` as labels on containers that are not the `ofelia` container itself?

From the code I've read it doesn't look like a technical limitation but rather a decision.

**Comment by Trane9991** [comment]
Well, the reasoning was the following:
- `job-exec` is an instruction to Ofelia to run a command inside some existing container and to do so, it needs the ID of the target container. Configuring it as labels on the target container completely makes sense.
- `job-local` is an instruction to Ofelia to run a command inside Ofelia container. Configuring it as labels for some other container will be confusing about **where** command will be executed. For example, when you see `nginx` container with `job-local` label, you may assume, that command will run inside `nginx` container, but no, it will be executed in the Ofelia container, because it is **local to Ofelia**
- `job-run` is an instruction to Ofelia to run command in the **new** one-time container. Again, configuring `job-run` as a label to the `nginx` container, one may assume that it will be somehow related to `nginx` container, but in reality, it will run in a completely new and unrelated container.

**Comment by mumrau** [comment]
While I think what you're saying makes sense about the potential confusion, I do believe however that `ofelia` should allow it nonetheless.

 There are a million reasons to want the `job-run` or `job-local`described in the labels of another container no matter where the code is being executed. First one being separation of concerns, if you want to run a backup container that is related to a piece of software, you want to be defining the backup _where_ you also describe the piece of software's workload. Having to describe every piece of container backup on the `ofelia` container itself is a major violation of such principles.
Think of `traefik` using `docker discovery`, and now imagine having to describe _your entire routing_ on the `traefik` container itself instead of as labels on the container that you actually want to route the traffic to. It doesn't really make sense, as you would have to alter `traefik` container itself (which could lead to downtime, errors, whatever) in order to modify `whatever-99th-container-i-want-to-route-traffic-to` network.

Making the potential confusion clear is probably a documentation effort, or maybe we need to add yet another label like "yes-i-mean-it" or whatever that describes that you understand the risk and want to proceed nonetheless.

If I may add, users of ofelia are probably not super-beginners in the whole containerization world, and they would understand without much hassle the change. On my end, I can't imagine having to overload my business containers with the logic for backup, because I do not want one to interfere with the other, which is exactly why I need `job-run`, and I think everything above explains why I need `job-run` to be described on the `docker-compose` of the workload, and not on `ofelia` container.

**Comment by cmsj** [comment]
I realise this discussion is very old, and on a closed issue, but I wanted to chime in for one specific use case - starting a stopped container.

Being able to set:

`ofelia.enabled=true
ofelia.job-run.schedule="@every 1h"`

on a one-shot container, would be amazingly helpful.
